// Generated by CozyScript 0.1.1
(function() {
  var allowCrossDomain, app, compile, express, fs, marked, nib, stylus, util;

  express = require('express');

  stylus = require('stylus');

  nib = require('nib');

  util = require('util');

  fs = require('fs');

  marked = require('marked');

  app = express();

  compile = function(str, path) {
    return stylus(str).set('filename', path).use(nib());
  };

  app.set('views', __dirname + '/views');

  app.set('view engine', 'jade');

  app.set('view options', {
    layout: false
  });

  app.use(express.logger());

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: "moe"
  }));

  app.use(stylus.middleware({
    src: __dirname + '/public',
    compile: compile
  }));

  app.use(express["static"](__dirname + '/public'));

  allowCrossDomain = function(req, res, next) {
    console.log('allowCrossDomain');
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Accept, Content-Type');
    return next();
  };

  app.use(function(error, req, res, next) {
    console.log(error);
    return res.send(500, {
      error: util.inspect(error)
    });
  });

  app.options('/api', allowCrossDomain);

  app.post('/api', allowCrossDomain);

  app.post('/api', function(req, res) {
    console.log(req.body.markdownstr);
    return marked(req.body.markdownstr, {}, function(err, parsed) {
      if (err) {
        return console.log(err);
      } else {
        return res.send({
          html: parsed
        });
      }
    });
  });

  app.listen(8080);

}).call(this);
